name: Convert README.md to PDF and Upload to Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex

      - name: Convert README.md to PDF
        run: |
          pandoc README.md -o README.html --css=style.css --pdf-engine=xelatex
          pandoc README.html -o README.pdf 

      - name: Upload PDF to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: README.pdf
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest
          name: README PDF Release

